#! /usr/bin/env python3
"""Cleans up orphaned HIS sessions."""

from his.orm import Session


def cleanup_sessions():
    """Cleans up orphaned sessions."""

    count = 0

    for count, session in enumerate(Session.cleanup(), start=1):
        print('Clearing session: {}.'.format(session))

    if count:
        print('Deleted {} orphaned sessions.'.format(count), flush=True)
    else:
        print('Nothing to do.', flush=True)


if __name__ == '__main__':
    cleanup_sessions()
