#! /usr/bin/env python3
"""HOMEINFO Integrated Services Daemon."""

from his.config import CONFIG
from his.wsgi import APPLICATION


if __name__ == '__main__':
    HOST = CONFIG['wsgi']['host']
    PORT = int(CONFIG['wsgi']['port'])
    APPLICATION.run(host=HOST, port=PORT)
